config/routes.rb
Pajaro::Application.routes.draw do
  root 'quotes#index'

  resources :quotes
  get 'sobre', to: 'quotes#sobre'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  validates :saying, presence: true, length: { maximum: 200, minimum: 3 }
  validates :author, presence: true, length: { maximum: 60, minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quote = Quote.order("RANDOM()").first
  end

  def create
    @quote = Quote.create(quote_params)
    if @quote.invalid?
      flash[:error] = '<strong>No se podia guardar,</strong> el frase ingresado es inválido.'
    end
    redirect_to root_path
  end

  def sobre
  end

  private

  def quote_params
    params.require(:quote).permit(:saying, :author, :country)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pajaro en mano</title>
  <meta charset="utf-8">
  <meta name="description" content="Un generador de refranes al azar. A random quote generator.">
  <meta name="keywords" content="refrán, refranes, dichos, frases, aleatorio, azar, generador, Español, idioms, sayings, proverbs, Spanish, random, quote, generator">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <header>
    <div class="col-xs-3">
      <%= link_to root_path, class: 'logo' do %>
        <div class="logo">
          <%= image_tag 'bird-in-hand-100px.jpg', class: 'img-responsive' %>
          <!-- <p id="fotoCredit">foto credito: fulano</p> -->
        </div>
      <% end %>
    </div>
    <div class="col-sm-4 hidden-xs slogan">
      Refránes queridas desde 2016
    </div>
    <div class="col-xs-8 col-xs-offset-1 col-sm-offset-0 col-sm-5 links">
      <!-- Button trigger modal -->
      <%= link_to 'Contribuir', new_quote_path, data: {toggle: 'modal', target: '#myModal'} %>
      &nbsp;&nbsp;&nbsp;
      <%= link_to 'Sobre', sobre_path %>
    </div>
  </header>


  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Su Consejo...</h4>
        </div>
        <%= simple_form_for Quote.new do |f| %>
        <div class="modal-body">
          <%= f.input :saying, label: "Un dicho o refrán favorito...", placeholder: "Más vale un pájaro en mano que ciento volando." %>
          <br>
          <%= f.input :author, label: "Quién es el que le encanta decir esto?", placeholder: "Fulano de la vuelta abajo, o su nombre" %>
          <br>
          <%= f.input :country, label: "País de origen..." %>
          <br>
          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
          <%= f.submit 'Crear', class: 'btn btn-success' %>
        </div>
        <% end %>  
      </div>
    </div>
  </div>




  <hr />
  <br class="clear" />

<div class="container">
  <% if flash[:error].present? %>
    <div class="col-xs-10 col-xs-offset-1 alert alert-danger">
      <%= flash[:error].html_safe %>
    </div>
  <% end %>
<%= yield %>
</div>

<div class="footer">
  <div class="container">
    <div class="col-xs-12 col-sm-6">
      <%= link_to "Otro más!", root_path, class: 'next-quote' %>
    </div>
    <div class="col-xs-12 col-sm-6 footer-blurb">
      Este sitio ha sido creado con mucho orgullo y amor en Orlando, FL departe de <a href="http://www.iseeincode.com">Benny Paulino</a>.
    </div>
  </div>
</div>


</body>
</html>

app/views/quotes/index.html.erb
<h3>
  <span>Consejo N<sup><u>o</u></sup> &nbsp;<%= @quote.id %></span>
  &nbsp;&nbsp;&nbsp;<span id="tagLine">El mejor consejo no solicitado que encontrará dondequiera!</span>
</h3>

<h1><%= @quote.saying %><h1>

<h2 class="pull-right">- <%= @quote.author %></h2>
<br class="clear" />
<!-- <h3 class="pull-right">- <%= @quote.country %></h3> -->

app/views/quotes/sobre.html.erb
<div class="col-xs-10 col-xs-offset-1">
  <h1>Sobre Pájaro en Mano...</h1>    

  <p>
    Pájaro en mano era creado por <a target="_blank" href="https://github.com/bennypaulino">Benny</a>. Hay muchos refranes que uno escucha departe de nuestros mayores, aquí los podemos compartir y reir un poco también.
  </p>

</div>

<br class="clear" />
<br>